### PR TITLE
Scrolling List

### PR DESCRIPTION
**Pull request by ahvuong**
The _scrolling list feature_ will be added based on the original **style.css** and **index.html** taken from the **button** branch for easily building up its positions on the homepage. This is how it works:
image

### CODE REVIEW

**Review by pdn002 — DISMISSED** [review]
Looks good. I assume the static list items are just there to show scrolling functionality and will be replaced later on.

**Comment by pdn002** [comment]
Actually I just realized something for the index.html file. The <nav> tags might not have to be inside the <form> tags since the scrolling list feature shouldn't need any user input from form tags. In might be better to structure like so
```
<section>
  <form>
  
  <\form>
  
  <nav>
      <ul>
  
      <\ul>
  <nav>
<\section>
```
Would like some opinions on this.

**Review by yac033 — APPROVED** [review]
Scrolling works on my end!

**Review by ZijianSuUCSD — APPROVED** [review]

**Review by pdn002 — APPROVED** [review]
Looks good, thanks for making changes

**Review by Emaneliforp — COMMENTED** [review]
I don't think the usage form or nav is appropriate here. I think you might be using nav as a vertical navbar but list should be sufficient. Form also isn't exactly necessary since there is no input. You can have button by itself.

**Comment by ahvuong** [comment]
> [Emaneliforp](/Emaneliforp)

The most recent version has been fixed without form and nav. In other words, `scrolling list` is now outside of `form` and is not inside `nav` like this:
image
image

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Comment by pdn002** [comment]
I saw that Jack said we will not need the form tag, so what ill do is merge this pull request with the scrolling list feature and fix the form and button tag on my button pull request.

**Pull request merged**
