### PR TITLE
for each item, update and delete on seperate line

### PR DESCRIPTION
**Pull request by pdn002**
List items now look like this
image
Update and delete button will always be on a separate line no matter the length of the list contents

### CODE REVIEW

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Review by ahvuong — APPROVED** [review]
I tested it and it worked on my end!

image

**Review by varunraisinghal — APPROVED** [review]
I like this change thank you very much.

**Comment by yac033** [comment]
So this PR is just making sure the update and delete is in the new line?

**Review by yac033 — APPROVED** [review]
Nice Good one!

**Pull request merged**
