### PR TITLE
Setup puppeteer and fixed syntax index.html and index.js

### PR DESCRIPTION
**Pull request by Emaneliforp**
- Added puppeteer and jest-pupperteer to package.json and created puppeteer config file
- Created e2e tests for creating item in shopping list
- Removed unnecessary newline in shopping list and inventory list (index.html)
- Removed unnecessary space at category when create item (index.js)

### CODE REVIEW

**Review by ZijianSuUCSD — APPROVED** [review]

**Review by varunraisinghal — APPROVED** [review]
Looks good. Puppeteer setup seems easy. Thank you.

**Comment by pdn002** [comment]
I don't understand how I'm supposed to run this. I keep getting the following error.
image

**Comment by Emaneliforp** [comment]
Paul, you have to cd to source before running npm cause package.json is in source

**Review by pdn002 — APPROVED** [review]
Works great on my end.
Note: I also had to run npm i to install some stuff before running test

**Review by mustaqs — APPROVED** [review]

**Pull request merged**
