### PR TITLE
Left align and clean-up frontend code

### PR DESCRIPTION
**Pull request by pdn002**
List of changes:
- Left align list items (was centered before)
- Added a title to the title tag in index.html (inside the head section that is not visible to users)
- Added documentation comments to hopefully make code more readable
  - Most of the comments are for the nav bar and the main section in style.css
- Moved some of the css selectors around so they are more intuitive.
  - All selectors related to nav bar are right next to each other instead of being 100 line apart
  - Selectors for elements that are at the top of our web page are also at the top of the css file; same is true for bottom
- <b> IMPORTANT:</b> got rid of the flex-container tag entirely
  - used main tag to implement the same functionality (imo seemed a little repetitive to have flex-container tag inside main tag)

This is mostly just documentation so the app should basically not be functionally different.

### CODE REVIEW

**Comment by pdn002** [comment]
All these code styling changes are completely subjective so please feel free to let me know if there is simply something you don't like.

**Review by ZijianSuUCSD — APPROVED** [review]
fixed the black background is not displayed when the button is clicked. The reason is that someone changed the id selector to a class selector.

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Comment by pdn002** [comment]
Looks like looks like pull request #99 branched of from this one so all these changes are already in that branch. However I would still like this branch to be merged first so that we don't have too many changes being merged at once.

**Review by ahvuong — APPROVED** [review]
It looks good and works on my end. However, just in my opinion, it would be better if we can set "Update" and "X" button in new line right after "item, quantity, and category" when we have extra time.

**Comment by pdn002** [comment]
> It looks good and works on my end. However, just in my opinion, it would be better if we can set "Update" and "X" button in new line right after "item, quantity, and category" when we have extra time.

Sound like a great idea. I already made an issue for the list formatting and will work on it in separate branch after all the the pull request are approved.

**Review by yac033 — APPROVED** [review]

**Pull request merged**
