### PR TITLE
Create UI and index UI - fix some bug

### PR DESCRIPTION
**Pull request by ZijianSuUCSD**
Improved the style of creat UI 

Changed the text of the add item button to a plus sign.

Bug:
After clicking the button, the black background that appears does not cover the entire page.

Bug fixed:
Create a new div and modify index.js. This fixes this problem.

*The screenshots don't show all modifications.

--------------
When the input in the creation UI is empty, prompt the user that the input cannot be empty.

### CODE REVIEW

**Comment by ZijianSuUCSD** [comment]
Fixed create UI style and added device adaptation.

image

image

**Review by Emaneliforp — DISMISSED** [review]
Looks good!

**Comment by pdn002** [comment]
Before I approve, why is the 'section' selector in the style.css file commented out? I assumed there was some other selector that replaced it so that we could still adjust the sizing of each list but I don't seem to see it.

**Comment by ZijianSuUCSD** [comment]
> Before I approve, why is the 'section' selector in the style.css file commented out? I assumed there was some other selector that replaced it so that we could still adjust the sizing of each list but I don't seem to see it.

at the bottom. Modified to display different arrangements for different screen sizes, vertical/horizontal.
image

**Review by pdn002 — APPROVED** [review]
Other than some commented out code still existing. Looks great.

**Review by pdn002 — APPROVED** [review]

**Review by ahvuong — APPROVED** [review]
All are good on my end except the commented-out codes in line 45 and from 168 to 181 which should be deleted.

**Review by yac033 — APPROVED** [review]

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Pull request merged**
