### PR TITLE
133 bug clean up backend codes and bugs

### PR DESCRIPTION
**Pull request by Emaneliforp**

### CODE REVIEW

**Comment by Emaneliforp** [comment]
- Made inventory update and get method not case sensitive
- Fixed syntax for index.js and delete.js
- Removed sum method and unit test (for jest testing)
- Fixed checkbox and remove button generated by suggestion item
- Fixed inventory add modal clearing input field
- Renamed addEvents to addShoppingEvents

**Review by yac033 — APPROVED** [review]
Works Great

**Review by ZijianSuUCSD — APPROVED** [review]
good

**Review by pdn002 — APPROVED** [review]

**Review by varunraisinghal — APPROVED** [review]
This is perfect. Thank you.

**Pull request merged**
