### PR TITLE
button on separate line and guide button visibility

### PR DESCRIPTION
**Pull request by pdn002**
- For each list item delete and update button should be on separate line.
- Should work when item is first added and after page refresh.
image

### CODE REVIEW

**Comment by pdn002** [comment]
The guide button is now black instead of being white. (More visible since background was white before)

**Review by Emaneliforp — APPROVED** [review]
Looks good

**Review by ZijianSuUCSD — APPROVED** [review]

**Review by varunraisinghal — APPROVED** [review]
Looks good. Nice fix

**Review by yac033 — APPROVED** [review]
Nice fix!

**Pull request merged**
