### PR TITLE
Button

### PR DESCRIPTION
**Pull request by pdn002**
List of changes:
- created skeleton for index.html
- renamed .css to style.css (going to look like deletion of .css and addition of style.css)
- created skeleton for for style.css
- added title ("Kaimono") to app
- Things added to shopping section
  - title
  - button
- things added to inventory section
  - title
  - button
- Added style that positions and spaces the title, shopping section, and inventory section

Page looks like this:
image

### CODE REVIEW

**Review by ahvuong — DISMISSED** [review]
Look good on my end! I will use your base to build up the scrolling list feature due to consistency and it's also easy to follow up based on what you did.

**Review by Emaneliforp — DISMISSED** [review]
Looks good.

**Comment by pdn002** [comment]
Removed the form tag from index.html like Jack suggested.
The functionality of the website remains unchanged.

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Review by ZijianSuUCSD — APPROVED** [review]

**Comment by mustaqs** [comment]
Looks good!

**Review by mustaqs — APPROVED** [review]

**Pull request merged**
