### PR TITLE
Fix the update button calling create method.

### PR DESCRIPTION
**Pull request by yac033**
1) Fix the bug that the update button calling create method instead of update method. 
2) removed all the input constrant

### CODE REVIEW

**Review by Emaneliforp — DISMISSED** [review]
Looks good!

**Review by varunraisinghal — APPROVED** [review]

**Review by ahvuong — DISMISSED** [review]

**Review by Emaneliforp — DISMISSED** [review]
Looks better!

**Comment by ZijianSuUCSD** [comment]
in 118-306, there still have many input numbers

image

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Review by ahvuong — APPROVED** [review]

**Review by ZijianSuUCSD — APPROVED** [review]

**Review by pdn002 — APPROVED** [review]

**Pull request merged**
