### PR TITLE
Combine style

### PR DESCRIPTION
**Pull request by pdn002**

### CODE REVIEW

**Comment by pdn002** [comment]
List of merging changes:
- '.wrapper' selector from '.css' file is completely gone
- '.navbar' selector from '.css' file is completely gone
  - <b> I suggest we work on creating the navigation bar in a separate issue/branch </b>
- Deleted some repetitive code ex:
  - ``` border-color: green``` ; when background is already green
  - ``` margin: 0 ``` ; when parent element already has this property

List of added changes (not a consequence of merging, I just felt like adding myself):
- added curved edges to each list
- Made each list height scale with height of browser window

Site currently looks like the following
image

**Review by Emaneliforp — APPROVED** [review]
Looks good for now. I noticed that everything is in px for now which is fine. But you should make them responsive eventually

**Review by ZijianSuUCSD — APPROVED** [review]

**Review by ahvuong — DISMISSED** [review]
Look good on my end now. We may need to change the color later.

**Comment by Subashkatel** [comment]
Changed a few stuff, added a nav bar, and made the nav bar responsive for mobile. The page is responsive but not centered still working on that.

image


image

image

**Review by Subashkatel — APPROVED** [review]

**Comment by Subashkatel** [comment]
change the colors to look little bit better is anyone has any suggestion would really appreciate 

here is what it looks like currently 

image

**Review by Subashkatel — DISMISSED** [review]

**Comment by pdn002** [comment]
I centered the two list to middle of page

**Review by ZijianSuUCSD — APPROVED** [review]
Judging by your latest style, I think it's good.  
But it still needs to be changed, you need to try to delete things in the list, so that it has the same size as if it were an empty list.

**Review by Subashkatel — APPROVED** [review]

**Review by Emaneliforp — APPROVED** [review]
looks good

**Review by ahvuong — APPROVED** [review]
Everything looks good on my end and it is good enough so far to get approved not but we may need to change the color a little bit later before submission.

**Pull request merged**
