### PR TITLE
Fixed suggest items button placement

### PR DESCRIPTION
**Pull request by pdn002**
<b>NOTE: This pull request is only for the position of button. Look and style of button can be done in seperate request </b>

#### High level overview of changes:
- removed the two suggest item button from top of shopping list section and inventory section
- suggest item button is now centered above and outside the two section
- Fixed bug where hovering over suggest button wasn't highlighting text

#### Low level overview of changes (for @ZijianSuUCSD since he worked on this part):
- The following changes are for the fact that there is only one button instead of two
   - Deleted eventListener for second suggest item button
   - changed class and id identifier for suggest button
   - Modified CSS and JS file to account for these change in identifiers 

#### site now looks like this
image

### CODE REVIEW

**Review by Emaneliforp — DISMISSED** [review]
Looks good!

**Comment by ZijianSuUCSD** [comment]
Can you add borders? Because the background color of this button is very similar to the background.

**Comment by pdn002** [comment]
After this request is merged ill create a new issue so that we can add things like color, borders and other aesthetics later.

**Review by ahvuong — COMMENTED** [review]
I think the `suggest items` button should be bigger if you leave it there or can we leave it next to the `guide` button?

**Comment by ZijianSuUCSD** [comment]
Added a border to the suggestion list button and completed the hamburger functionality.
image

image

**Review by ZijianSuUCSD — APPROVED** [review]

**Comment by pdn002** [comment]
There is till an error with reverting the changes.
<b> don't approve this yet </b>

**Comment by pdn002** [comment]
To revert the changes to commit [35b9547](https://github.com/cse110-fa22-group22/cse110-fa22-group22/pull/132/commits/35b9547f442c6dc5fa8c15d7be033f0eaeb404a3)

**Pull request closed without merging**
