### PR TITLE
Shopping List: Create Method

### PR DESCRIPTION
**Pull request by ZijianSuUCSD**
index.html

- Index.js is connected in index.html, and a dialog box is added.

style.css

- The dialog style and span style are added to style.css.

index.js

- Since I didn't understand how to write the script in create.js and it can be called by index.js, so I wrote the script to create the item in index.js, hoping to fix it later.

### CODE REVIEW

**Comment by Emaneliforp** [comment]
Fixed:
- Removed default margin and padding
- Changed functions and ids naming
- Changed modal to form
- Added background to make modal more standout
- Added modal closure by clicking outside of the modal
- Improved the method of adding new item to list
- Implemented create method and store shoppingList in localStorage

**Review by yac033 — DISMISSED** [review]

**Review by yac033 — DISMISSED** [review]

**Review by mustaqs — DISMISSED** [review]

**Review by mustaqs — DISMISSED** [review]
Works as expected

**Comment by Emaneliforp** [comment]
Removed UI components and added unit test

**Review by varunraisinghal — DISMISSED** [review]

**Review by yac033 — APPROVED** [review]

**Review by pdn002 — APPROVED** [review]
I looked through the css and it doesn't seem like it will conflict with the the other merge style pull request.

**Review by ahvuong — APPROVED** [review]

**Comment by pdn002** [comment]
I just merged the combine_style branch so that why there is a merge conflict. I took a look at the conflicts and nothing looks too critical. All the conflicts are added change that we should want to keep so no lines should really need any deletion or change. I would still like a second opinion from someone who worked on the create method just to be sure though.

**Review by varunraisinghal — APPROVED** [review]

**Review by pdn002 — APPROVED** [review]
<b> From front end view </b> (didn't work on backend), all the style in css file looks good.

**Review by ahvuong — APPROVED** [review]

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Pull request merged**
