### PR TITLE
Completed the feature to suggest listings to add to the inventory list. Modified some styles and added a home page.

### PR DESCRIPTION
**Pull request by ZijianSuUCSD**
Items can now be added to inventory using the button in the suggestion list.
image

CSS changes: 
Buttons in the suggestion list now change color when the mouse is over them.

The button in the suggestion list becomes larger from the input box above it. And the button position is centered.
image

html changes: 
Changed the color of the question mark as suggested
image

Suggested list text changed to SUGGESTED ITEMS

Fixed a typo in the inventory input module
image

The opening method of the about page has been changed. Clicking this button will not open a new page, and the current page will become the about page.
image

Added a back button to the about page to return to the list page. and center the introductory text
image

Added a homepage. Click the middle button on the home page to go to the list page.
image

Added 2 css files. One is text animation css, the other is home page css. The source has been written on the comment.
[text animation](https://animate.style/)
[home animation](https://www.sliderrevolution.com/resources/css-animated-background/)

Fixed the bug that the hamburger menu would still be displayed on a large screen after opening the hamburger menu on a small screen.

### CODE REVIEW

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Review by varunraisinghal — APPROVED** [review]
Great fixes. Thank you. Approved

**Review by Emaneliforp — DISMISSED** [review]
Looks good!

**Review by ahvuong — CHANGES_REQUESTED** [review]
image
I found a typo here on `About` page. Can you please fix it?

**Review by mustaqs — APPROVED** [review]

**Comment by varunraisinghal** [comment]
> image I found a typo here on `About` page. Can you please fix it?

Nice catch on this error. Re-approved.

**Review by ahvuong — DISMISSED** [review]
image
Also, the item was not added to the `Inventory List` after clicking `OK` on the alert window popped up.

**Review by varunraisinghal — APPROVED** [review]

**Comment by ZijianSuUCSD** [comment]
image
 fixed typo and some issues

**Review by ahvuong — APPROVED** [review]

**Review by varunraisinghal — APPROVED** [review]

**Review by pdn002 — APPROVED** [review]

**Review by Emaneliforp — APPROVED** [review]
Looks good

**Pull request merged**
