### PR TITLE
Sugges list and UI upgrade

### PR DESCRIPTION
**Pull request by ZijianSuUCSD**
This branch is based on the branch **left-align**. This branch has not been merged yet. 11/26/2022

## Update details

A new user guide has been created. Clicking it lets the user know what each button does.
image
image

Added button for suggest list
image

Click it to see some preset items. Use different buttons to add these items to different lists.
image

Can successfully add item to shopping list. I simply call the add function on the shopping list.
image
image

**Since the inventory has not yet completed the adding function, clicking the orange button has no effect. Need to wait for the person in charge of the inventory to complete the add function.**

Changed the style of the list. Removed the scrollbar for the X axis as it is not needed.
image

The scrollbar changes color when the mouse is over it, as do the guide and suggest list buttons.
image

Added wavy background(quote from the [web](https://codepen.io/baarbaracrr/pen/KKovmGb)).
image

The creation UI has been revised again, and the new font is improted from Google font
image

Add link. Clicking on these 2 links will take you to 2 of our GitHub pages.
image

Add an icon.
image

## BUG fixed
The quantity entered now needs to be greater than 0.

Fixed the bug that things will still be added when the judgment fails.

### CODE REVIEW

**Review by varunraisinghal — APPROVED** [review]

**Review by Emaneliforp — COMMENTED** [review]
Looks really cool overall! I only have a few styling suggestions.

1. I don't think you need ul::-webkit-scrollbar-thumb:horizontal.

2. Keeping all border-radius 10px (ul, li) is better. They look a bit messy.

3. For ul::-webkit-scrollbar-track, if you are trying to hide it, instead of making it white like the background, you can make it transparent `background-color: rgba(0,0,0,0);`.

4. For webkit-scrollbar-thumb, curved on one corner is unconventional. It is better to keep it `border-radius: 20px;`.

**Review by ahvuong — DISMISSED** [review]
All work perfect on my end but I have just few minor styling suggestions: 
1. The items are added through functions ("suggestAddShoppingItem") from line 319 to 369 in index.js; their first character should be changed to upper case.
2. The second column in "User Guide" should have left align and we need a litte space between 2 columns.
3. Can the wave be moved up a little bit near the middle page?
4. As I mentioned before, I still think we need to change the background color to a new brighter one. If I'm not wrong, Navya talked about our background color in the last meeting too. This is just so minor thing and I can create another issue for this to do right after your PR get merged to avoid conflict.

**Comment by ZijianSuUCSD** [comment]
image

**Comment by ZijianSuUCSD** [comment]
image

**Review by ahvuong — DISMISSED** [review]

**Review by ahvuong — DISMISSED** [review]

**Review by varunraisinghal — DISMISSED** [review]

**Review by pdn002 — APPROVED** [review]
I see some very minor issues but I'll save them for a separate pull request.

**Review by yac033 — APPROVED** [review]

**Review by yac033 — APPROVED** [review]

**Review by varunraisinghal — APPROVED** [review]

**Review by pdn002 — APPROVED** [review]

**Review by Emaneliforp — APPROVED** [review]
Looks good!

**Pull request merged**
